Feature filipau
rakovets/workshop-git pull request #1
Opened 2021-01-10 15:31 UTC by FilippovZ

2021-01-11 14:25 UTC, Eugenoil approved these changes

2021-01-11 14:26 UTC, tanya-java approved these changes

2021-01-11 14:31 UTC, phrismin approved these changes

2021-01-11 14:31 UTC, OxanaPeregud approved these changes

2021-01-11 14:32 UTC, Semargl92 approved these changes

2021-01-11 14:32 UTC, Semargl92 commented on git-for-beginners-part-2-install-git.adoc
> +Fedora
Не знаю, насколько это важно - но в оригинальном тексте (Fedora 21) с новой строки

2021-01-11 19:51 UTC, rakovets requested changes
Калі ласка, выправіце ніжэйапісанныя праблемы і аналагічныя ім.

2021-01-11 19:51 UTC, rakovets commented on git-for-beginners-part-2-install-git.adoc
> +== Git для начинающих. Часть 2. Установка Git
Чаму header 2, а не header 1?

Уплывае на ўсе ніжнія headers.

2021-01-11 19:51 UTC, rakovets commented on git-for-beginners-part-2-install-git.adoc
> +image::/img/git-part2-1.jpg[]
Нельга па назве файлаў вызначыць што на ім адлюстравана.
Не дадазены альтэрнатыўны тэкст на выпадак калі адсутнічае малюнак.

2021-01-11 19:51 UTC, rakovets commented on git-for-beginners-part-2-install-git.adoc
> +==== *1. Запустить установочный файл*
Непатрэбнае дадатковае выдзяленне для headers. Ніжэй таксама.

2021-01-11 19:51 UTC, rakovets commented on index.adoc
> +include::git-for-beginners-part-2-install-git.adoc[]
Дрэннае імя для файла, лепей проста усталяванне git.

2021-01-11 19:51 UTC, rakovets commented on git-for-beginners-part-2-install-git.adoc
> +> apt-get install git
Дрэнная стылістыка ў аўтара topic. Выдаліць усе `>` - яны будуць толькі перашкаджаць выкарыстанне каманд.
```suggestion
apt-get install git
```

2021-01-11 19:51 UTC, rakovets commented on git-for-beginners-part-2-install-git.adoc
> +[source, sh]
Лепей будзе:
```suggestion
[source,shell script]
```

2021-01-12 09:32 UTC, FilippovZ commented on git-for-beginners-part-2-install-git.adoc
> +image::/img/git-part2-1.jpg[]
а как нужно называть файлы?

2021-01-12 10:48 UTC, rakovets requested changes

2021-01-12 10:48 UTC, rakovets commented on install-git.adoc
> +=== 2. Ознакомиться, если есть желание, с лицензионным соглашением и нажать на кнопку Next
```suggestion
=== Запустить установочный файл

=== Ознакомиться, если есть желание, с лицензионным соглашением и нажать на кнопку Next
```

2021-01-12 10:48 UTC, rakovets commented on install-git.adoc
> += Git для начинающих. Часть 2. Установка Git
Занадта шмат дарэмнай інфармацыі, толькі тое, пра што дадзеная тэма.
```suggestion
= Установка Git
```

2021-01-12 10:48 UTC, rakovets commented on index.adoc
> +include::git-for-beginners-part-8.adoc[]
Асаблівасці пры аб'яднанні некалькіх топікаў у адзін.

```suggestion
include::install-git.adoc[]

include::git-for-beginners-part-8.adoc[]
```

2021-01-14 14:26 UTC, rakovets requested changes
Добра, але патрэбна яшчэ выправіць яшчэ некалькі заўваг.

2021-01-14 14:26 UTC, rakovets commented on install-git.adoc
> +=== 2. Ознакомиться, если есть желание, с лицензионным соглашением и нажать на кнопку Next
Выдаліць нумары для Headers, таму што яны праставяцца самастойна ў Table of Content

2021-01-14 14:26 UTC, rakovets commented on install-git.adoc
>  Debian/Ubuntu
Дадай header 3 узроўню для каждай OS

2021-01-14 14:26 UTC, rakovets commented on install-git.adoc
>  Debian/Ubuntu
```suggestion
=== Debian/Ubuntu
```

2021-01-15 11:08 UTC, FilippovZ commented on install-git.adoc
> +=== 2. Ознакомиться, если есть желание, с лицензионным соглашением и нажать на кнопку Next
попробовал удалить номера, сами они автоматом не проставились

2021-01-15 11:16 UTC, FilippovZ commented on install-git.adoc
>  Debian/Ubuntu
если я вместо header 2 (как сейчас) поставлю header 3, то где тогда header 2 будут? Если ты хотел написать 2-го уровня добавить, то у меня как раз так. Хотя у тебя в части кода показывается, что нет. Не знаю почему.

2021-01-17 06:23 UTC, rakovets commented on install-git.adoc
> +=== 2. Ознакомиться, если есть желание, с лицензионным соглашением и нажать на кнопку Next
Для гэтага файла яны не праставяцца, але для таго файла, дзе ёсць Table of Contents.

2021-01-17 06:27 UTC, rakovets requested changes

2021-01-17 06:27 UTC, rakovets commented on install-git.adoc
> +=== 1. Запустить установочный файл
Выдаліць нумары, так як ў файле, дзе ёсць Table of Contents, для іх праставіцца нумарацыя.

2021-01-17 06:27 UTC, rakovets commented on install-git.adoc
> +== Debian/Ubuntu
Для кожнай OS праставіць HEADER ніжэй чым для ```== Установка Git под Linux```  таму што гэта падпункты для яе. Паставіць HEADER 3.

2021-01-18 20:17 UTC, rakovets approved these changes
Збяры апрувы. Затым вырашы анфлікты зліця і можна рабіць зліцё.

2021-01-18 22:21 UTC, merged