feature-rudoi / it-academy.by / M-JC1-66-20 / Aliaksei Rudoi / Done workshop-git
rakovets/workshop-git pull request #2
Opened 2021-01-10 16:38 UTC by phrismin

2021-01-10 23:00 UTC, FilippovZ approved these changes

2021-01-11 13:50 UTC, FilippovZ approved these changes

2021-01-11 14:03 UTC, tanya-java approved these changes

2021-01-11 14:04 UTC, OxanaPeregud approved these changes

2021-01-11 14:21 UTC, Semargl92 approved these changes

2021-01-11 14:27 UTC, Eugenoil approved these changes

2021-01-11 19:56 UTC, rakovets requested changes
Калі ласка, выпраўце апісанныя ніжэй праблемы і аналагічныя ім.

2021-01-11 19:56 UTC, rakovets commented on git-for-beginners-part-4-git-arch.adoc
> +=== Git для начинающих. Часть 4. Архитектура Git
Чаму header 3, а не Header 1?

2021-01-11 19:56 UTC, rakovets commented on git-for-beginners-part-4-git-arch.adoc
> +image::img/git-for-beginners-part4-pic1.png[]
Па назве файла немагчыма усталяваць, што на гэтым файле адлюстравана.

Не дадзены альтэрнатыўны тэкст, для выпадку калі незагрузіцца малюнак.

2021-01-11 19:56 UTC, rakovets commented on git-for-beginners-part-4-git-arch.adoc
> +. Повторить необходимое количество раз пункты 2 и 3.
лепей выкарыстоўваць `*`

2021-01-11 19:56 UTC, rakovets commented on index.adoc
> +include::git-for-beginners-part-4-git-arch.adoc[]
Назва файла мае занадта вялікае апісанне.

2021-01-13 11:18 UTC, Eugenoil approved these changes

2021-01-14 14:30 UTC, rakovets requested changes
Не ўсе выправлена.

2021-01-14 14:30 UTC, rakovets commented on git-for-beginners-part-4-git-arch.adoc
> +==== *Архитектура трех деревьев*
Header 1, а далей адразу Header 4?!

2021-01-14 14:30 UTC, rakovets commented on git-for-beginners-part-4-git-arch.adoc
> +==== *Архитектура трех деревьев*
```suggestion
== Архитектура трех деревьев
```

2021-01-14 14:30 UTC, rakovets commented on git-for-beginners-part-4-git-arch.adoc
> +image::img/git-for-beginners-part4-pic1.png[]
Назва файла усё яшчэ дрэнная, так па ён нічога нега сказаць. Па назве файла, патрэбна разумець што там за кантэтнт.

2021-01-17 06:31 UTC, rakovets requested changes
Неабходна зрабіць змены апісанныя ніжэй.

2021-01-17 06:31 UTC, rakovets commented on index.adoc
> +include::git-part-4.adoc[]
Назва файла не дае зразумець, які кантэнт нясе ў сабе файл. Неабходна змяніць назву.

2021-01-17 06:31 UTC, rakovets commented on git-part-4.adoc
> +чтобы понимать суть действий, которые мы будем совершать в дальнейшем.
Чаму адзін і той жа сказ, разнесены на некалькі радкоў? Патрэбна выправіць тут і ніжэй.

2021-01-18 20:19 UTC, rakovets approved these changes
Збяры апрувы. Затым вырашы канфлікты зліця і можна рабіць зліцё.

2021-01-19 18:26 UTC, merged