feature-peregud / it-academy.by / M-JC1-66-20 / Oxana Peregud / Done workshop-git
rakovets/workshop-git pull request #3
Opened 2021-01-10 18:47 UTC by OxanaPeregud

2021-01-10 23:01 UTC, FilippovZ approved these changes

2021-01-11 13:52 UTC, FilippovZ approved these changes

2021-01-11 13:58 UTC, Semargl92 approved these changes

2021-01-11 14:25 UTC, tanya-java approved these changes

2021-01-11 14:28 UTC, Eugenoil approved these changes

2021-01-11 14:35 UTC, phrismin approved these changes

2021-01-11 20:05 UTC, rakovets requested changes
Калі ласка, выпраўце ніжэйапісанныя праблемы і аналагічныя ім.

2021-01-11 20:05 UTC, rakovets commented on git-for-beginners-part-5.adoc
> +
Лішні пусты радок.

2021-01-11 20:05 UTC, rakovets commented on git-for-beginners-part-5.adoc
> +[source, sh]
Лепей вось так 
```suggestion
[source,shell script]
```

2021-01-11 20:05 UTC, rakovets commented on git-for-beginners-part-5.adoc
> +> mkdir repo
У аўтара topic дрэнны стыль па афармленню каманд. Выправіць аналагічныя.
```suggestion
mkdir repo
```

2021-01-11 20:05 UTC, rakovets commented on git-for-beginners-part-5.adoc
> +fatal: your current branch 'master' does not have any commits yet
```suggestion
[source,shell script]
git log

fatal: your current branch 'master' does not have any commits yet
```

2021-01-11 20:05 UTC, rakovets commented on git-for-beginners-part-5.adoc
> +Добавим, созданный файл в _stage_. _Stage_ (или _cache_) – это хранилище для файлов с изменениями, информация о которых попадет в единый коммит. _Stage_ является элементом архитектуры трех деревьев,
Лепей выдаліць перакрыжаваныя спасылкі, так як цяжэй рэфактарыць дакументацыю.

2021-01-11 20:05 UTC, rakovets commented on index.adoc
> +include::git-for-beginners-part-5.adoc[]
Назва  файла не гаворыць пра тое, што ў ім знаходзіцца.

2021-01-13 12:03 UTC, Eugenoil approved these changes

2021-01-14 14:35 UTC, rakovets approved these changes
Good job!
Resolve merge-conflicts and merge it.

2021-01-15 06:59 UTC, merged