feature-dunin / it-academy.by / M-JC1-66-20 / Eugene Dunin / Done workshop-git
rakovets/workshop-git pull request #4
Opened 2021-01-11 00:22 UTC by Eugenoil

2021-01-11 14:09 UTC, OxanaPeregud approved these changes

2021-01-11 14:24 UTC, tanya-java approved these changes

2021-01-11 14:29 UTC, FilippovZ approved these changes

2021-01-11 14:37 UTC, phrismin approved these changes

2021-01-11 14:43 UTC, Semargl92 approved these changes

2021-01-11 14:43 UTC, Semargl92 commented on git-for-beginners-part-7-head-and-tree-ish.adoc
> +c185b80 [create]: header for main
команды в коде отображает цветом (for, command, etc).

2021-01-12 10:27 UTC, rakovets requested changes
Патрэбна выправіць заўвагі і аналагічныя месцы.

2021-01-12 10:27 UTC, rakovets commented on git-for-beginners-part-7-head-and-tree-ish.adoc
> +== Git для начинающих. Часть 7. Поговорим о HEAD и tree-ish
чаму выкарыстоўваў Header 2, а не Header 1? Уплывае і на ніжэй прыведенныя.

2021-01-12 10:27 UTC, rakovets commented on git-for-beginners-part-7-head-and-tree-ish.adoc
> +* <<anchor-2,_Tree-is_>>
Па ссылках немагчыма зразумець да якога кантэнту яны прывязаныя.

2021-01-12 10:27 UTC, rakovets commented on git-for-beginners-part-7-head-and-tree-ish.adoc
> +[source, sh]
```suggestion
созданному в рамках link:https://devpractice.ru/git-for-beginners-part-6-git-log-work/[предыдущей статьи], в этом репозитории сделано шесть коммитов, посмотрим на них.

[source, sh]
```

2021-01-12 10:27 UTC, rakovets commented on git-for-beginners-part-7-head-and-tree-ish.adoc
> +a98cce4 [create repository]
Няправільнае выкарыстанне блока з кодам.
```suggestion
[source, sh]
----
git log --oneline
cf3d9d8 [add] ignore .tmp files
a7b88ee [create]: git ignore file
c185b80 [create]: header for main
2b826bb [create]: main file of programm
bc067c8 [add]: caption into README file
a98cce4 [create repository]
----
```

2021-01-12 10:27 UTC, rakovets commented on git-for-beginners-part-7-head-and-tree-ish.adoc
> +image::/img/git-head-pic1.png[]
Назвы файлаў не нясуць ніякая інфарматыўнасці., нельга вызначыць што там знаходзіцца.

Не дадазены альтэрнатыўны тэкст, на выпадак, калі малюнак не загрузіцца.

2021-01-12 10:27 UTC, rakovets commented on git-for-beginners-part-7-head-and-tree-ish.adoc
> +> ls -la
Дрэнна аўтар апісаў у topic каманды для shell script
```suggestion
cd .git
ls -la
```

2021-01-12 10:27 UTC, rakovets commented on git-for-beginners-part-7-head-and-tree-ish.adoc
> +[source, sh]
```suggestion
[source, shell script]
```

2021-01-12 10:27 UTC, rakovets commented on index.adoc
> +include::git-for-beginners-part-7-head-and-tree-ish.adoc[]
Дрэнная назва для файла. Сюды уключана і назва агульнай тоэмы і частка для агульная тэмы.

2021-01-17 06:36 UTC, rakovets requested changes
Зрабіць неабходныя выпраўленні, апісанныя ніжэй.

2021-01-17 06:36 UTC, rakovets commented on head-and-tree-ish.adoc
> += Поговорим о HEAD и tree-ish
Назвы headers, тэкст не павінны трымаць "вады":  "Поговорим", "мы можем убедиться" і г.д.

2021-01-17 06:36 UTC, rakovets commented on head-and-tree-ish.adoc
> +== _HEAD_ [[HEAD]]
Не патрэбна выдзяляць headers, толькі калі гэта код
```suggestion
== `HEAD` [[HEAD]]
```

2021-01-18 20:21 UTC, rakovets approved these changes
Збяры апрувы. Затым вырашы канфлікты зліця і можна рабіць зліцё.

2021-01-19 10:25 UTC, merged