feature-yermalitskaya/it-academy/M-JC1-66-20/Tanya Yermalitskaya/ Done workshop-git
rakovets/workshop-git pull request #6
Opened 2021-01-11 13:33 UTC by tanya-java

2021-01-11 14:30 UTC, OxanaPeregud approved these changes

2021-01-11 14:33 UTC, Eugenoil approved these changes

2021-01-11 14:40 UTC, phrismin approved these changes

2021-01-11 14:47 UTC, FilippovZ approved these changes

2021-01-11 14:51 UTC, Semargl92 approved these changes

2021-01-11 14:51 UTC, Semargl92 commented on git-for-beginners-part-6.adoc
> +В прошлом уроке мы разобрались с тем, как фиксировать изменения в рабочей директории и отправлять коммиты в репозиторий. Рабочий процесс с использованием _git_, в упрощенном виде, выглядит следующим
Тут в оригинальном тексте ссылка на другие статьи, не знаю, насколько она для нас важна в нашем проекте

2021-01-11 14:51 UTC, Semargl92 commented on git-for-beginners-part-6.adoc
> +В процессе работы, в вашем репозитории накопится больше количество коммитов и довольно часто будет возникать необходимость их просматривать. _Git_ предоставляет удобный способ просмотра информации по
Тут тоже в оригинальном тексте вложенная ссылка на другую страницу

2021-01-12 10:34 UTC, rakovets requested changes
Выправіць заўвагі і аналагічныя праблемы.

2021-01-12 10:34 UTC, rakovets commented on git-for-beginners-part-6.adoc
> +== Git для начинающих. Часть 6. Просмотр информации по коммитам
Чаму Header 2, a не Header 1?

2021-01-12 10:34 UTC, rakovets commented on git-for-beginners-part-6.adoc
> +. Формирование и отправка коммита на базе того, что лежит в _stage_, в репозиторий.
Лепшая практыка.

```suggestion
* Внесение изменений в рабочую директорию.
* Отправка изменений в _stage_.
* Формирование и отправка коммита на базе того, что лежит в _stage_, в репозиторий.
```

2021-01-12 10:34 UTC, rakovets commented on git-for-beginners-part-6.adoc
> +----
Чаму не пазначана што гэта?
```suggestion
[source,shell script]
----
git log
commit a98cce47b59256d00a853c421af4f7b9f0dc0a29
Author: Writer <writer@somecompany.com>
Date:   Mon Mar 5 23:10:51 2018 +0500

    [create repository]
----
```

2021-01-12 10:34 UTC, rakovets commented on git-for-beginners-part-6.adoc
> +----
Аўтар тэмы выкарыстоўвае не самую лепшую практыка для каманд shell script:

```suggestion
----
echo "Project 51" > README.md
----
```

2021-01-12 10:34 UTC, rakovets commented on git-for-beginners-part-6.adoc
> +====
Remove it!

2021-01-12 10:34 UTC, rakovets commented on index.adoc
> +include::git-for-beginners-part-6.adoc[]
Дрэнная назва для файла, не інфарматыўная, ад слова сузім.

2021-01-12 10:34 UTC, rakovets commented on READMe.adoc
>  9. Загружаем изменения в удаленый репозиторий.
Чаму правіцца гэтае месца?

2021-01-18 20:23 UTC, rakovets requested changes
Зрабіць выпраўленні для назвы файла і яго title.

2021-01-18 20:23 UTC, rakovets commented on git-for-beginners-part-6.adoc
> += Git для начинающих. Часть 6. Просмотр информации по коммитам
```suggestion
= Просмотр информации по коммитам
```

2021-01-21 19:26 UTC, rakovets requested changes
Патрэбна выправіць і можна мержыць.

2021-01-21 19:26 UTC, rakovets commented on git-for-beginners-part-6.adoc
> +----
```suggestion
----
git log
----

----
commit a98cce47b59256d00a853c421af4f7b9f0dc0a29
Author: Writer <writer@somecompany.com>
Date:   Mon Mar 5 23:10:51 2018 +0500

    [create repository]
----
```

2021-01-21 19:26 UTC, rakovets commented on git-for-beginners-part-6.adoc
> +----
Ужо добра, патрэбна яшчэ раздзяліць каманды і  вывад у кансоль, я паказана вышэй.

2021-02-03 13:06 UTC, rakovets approved these changes
Need to fix merge conflict and you can merge.

2021-02-03 13:08 UTC, Eugenoil approved these changes

2021-02-03 13:20 UTC, FilippovZ approved these changes

2021-02-03 13:25 UTC, Semargl92 approved these changes

2021-02-03 13:28 UTC, OxanaPeregud approved these changes

2021-02-05 08:51 UTC, Grin-s approved these changes

2021-02-09 15:29 UTC, merged